# Generated by Django 3.0.3 on 2020-02-28 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos_personales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos_personales',
            name='numero_registro',
        ),
        migrations.RemoveField(
            model_name='datos_personales',
            name='telefono',
        ),
    ]
