# Generated by Django 3.0.3 on 2020-02-28 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_personales', '0002_auto_20200228_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_personales',
            name='image_url',
            field=models.CharField(default='https://www.flickr.com/photos/56240096@N07/34872421446/', max_length=2083),
            preserve_default=False,
        ),
    ]
