# Generated by Django 3.0.3 on 2020-03-01 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_personales', '0003_datos_personales_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lugar_trabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar_trabajo', models.CharField(max_length=255)),
            ],
        ),
    ]
